Feature/function
appulegugure/php_exercise01 pull request #8
Opened 2022-02-28 09:19 UTC by appulegugure

確認お願いします。

2022-02-28 22:06 UTC, kazu-taka requested changes
@appulegugure 
コメントしたので確認お願いします😊

2022-02-28 22:06 UTC, kazu-taka commented on 08/function_2.php
> +    return $arry_sum;
@appulegugure 
連想配列の値を合算する関数がPHPでは存在するので、調べて使ってみて下さい✨

2022-02-28 22:06 UTC, kazu-taka commented on 08/function_5.php
> +    </form>
@appulegugure 
HTMLはなるべくdobyタグ内に書くようにして下さい😊
制御する部分を関数にして、その戻り値としてHTMLタグを返すのであれば、ヒアドキュメント内に記述してもOKです！

2022-03-01 00:36 UTC, kazu-taka commented on 08/function_2.php
> +    return array_sum(array_values($total_meals));
@appulegugure 
今回のように単純な連想配列の時は、そのままarray_sumだけで計算可能です✨
修正後マージしてOKです👍
![image](https://user-images.githubusercontent.com/5278718/156082331-475f938e-e774-434b-95aa-f95bda2aea7f.png)
👍

2022-03-01 00:55 UTC, appulegugure commented on 08/function_2.php
> +    return array_sum(array_values($total_meals));
なるほどarray_sumで計算出来るんですね。ありがとうございます。

2022-03-01 00:57 UTC, merged